### ISSUE TITLE
Errors report

### ISSUE THREAD

**Issue by cnnjqzr** [chantera/blstm-cws#1]
In model.py, it has several errors. Firstly, 'ImportError: cannot import name 'argsort_list_descent' 'happens when using 'from chainer.links.connection.n_step_lstm import argsort_list_descent, permutate_list' this import. Also, after I fix this problem manually, the model still has some problem inside, for example TypeError on lstm model. Could you run it again? I think maybe you forgot to change something. Thx!

**Comment by chantera** [comment]
Thank you for reporting.
These problems happen due to the difference of the versions of Chainer.
The programs work on the Chainer v1.18.0 and will not be maintained.

**Comment by cnnjqzr** [comment]
Thanks.
I have tried this code on  Chainer v1.22.0 and it works.

**Comment by chantera** [comment]
👍
